/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___network_WLAN__H
#define ___network_WLAN__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__network_WLAN(Args *args);

void _network_WLAN___init__(PikaObj *self, int interface_id);
void _network_WLAN_active(PikaObj *self, int is_active);
int _network_WLAN_checkActive(PikaObj *self);
Arg* _network_WLAN_checkConfig(PikaObj *self, char* param);
PikaObj* _network_WLAN_checkIfconfig(PikaObj *self);
void _network_WLAN_close(PikaObj *self);
void _network_WLAN_config(PikaObj *self, PikaDict* kwargs);
void _network_WLAN_connect(PikaObj *self, char* ssid, char* key);
void _network_WLAN_connectWithBssid(PikaObj *self, char* ssid, char* key, char* bssid);
void _network_WLAN_disconnect(PikaObj *self);
void _network_WLAN_ifconfig(PikaObj *self, char* ip, char* mask, char* gateway, char* dns);
int _network_WLAN_isconnected(PikaObj *self);
PikaObj* _network_WLAN_scan(PikaObj *self);
int _network_WLAN_status(PikaObj *self);
int _network_WLAN_statusWithParam(PikaObj *self, char* param);

#endif
