/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_canvas__H
#define __pika_lvgl_canvas__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_canvas(Args *args);

void pika_lvgl_canvas___init__(PikaObj *self, PikaObj* parent);
void pika_lvgl_canvas_copy_buf(PikaObj *self, uint8_t* to_copy, int x, int y, int w, int h);
void pika_lvgl_canvas_fill_bg(PikaObj *self, PikaObj* color, int opa);
PikaObj* pika_lvgl_canvas_get_img(PikaObj *self);
void pika_lvgl_canvas_get_px(PikaObj *self, int x, int y, PikaObj* color, int opa);
void pika_lvgl_canvas_set_buffer(PikaObj *self, uint8_t* buf, int w, int h, int cf);
void pika_lvgl_canvas_set_palette(PikaObj *self, int id, int c);
void pika_lvgl_canvas_set_px(PikaObj *self, int x, int y, PikaObj* color, int opa);
void pika_lvgl_canvas_transform(PikaObj *self, PikaObj* img, int angle, int zoom, int offset_x, int offset_y, int pivot_x, int pivot_y, PIKA_BOOL antialias);

#endif
